# Generated by Django 5.2.12 on 2026-03-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_environment_created_environment_last_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("provider", models.SlugField(help_text="Registered secrets backend provider slug.", max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific retrieval parameters, not the secret value itself.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("last_rotated", models.DateTimeField(blank=True, null=True)),
                ("expires", models.DateTimeField(blank=True, null=True)),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="tenancy.environment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="tenancy.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("organization__name", "workspace__name", "environment__name", "name"),
            },
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("environment__isnull", False)),
                fields=("environment", "provider", "name"),
                name="integrations_secret_unique_environment_provider_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("environment__isnull", True), ("workspace__isnull", False)),
                fields=("workspace", "provider", "name"),
                name="integrations_secret_unique_workspace_provider_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("environment__isnull", True), ("workspace__isnull", True)),
                fields=("organization", "provider", "name"),
                name="integrations_secret_unique_organization_provider_name",
            ),
        ),
    ]
