# Generated by Django 5.2.12 on 2026-03-30 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_secretgroup'),
        ('tenancy', '0002_environment_created_environment_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.SlugField(help_text='Stable role or key for this secret within the group.', max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_group_assignments', to='tenancy.environment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_group_assignments', to='tenancy.organization')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='integrations.secret')),
                ('secret_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='integrations.secretgroup')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_group_assignments', to='tenancy.workspace')),
            ],
            options={
                'ordering': ('organization__name', 'workspace__name', 'environment__name', 'secret_group__name', 'order', 'key'),
            },
        ),
        migrations.AddField(
            model_name='secretgroup',
            name='secrets',
            field=models.ManyToManyField(blank=True, related_name='secret_groups', through='integrations.SecretGroupAssignment', to='integrations.secret'),
        ),
        migrations.AddConstraint(
            model_name='secretgroupassignment',
            constraint=models.UniqueConstraint(fields=('secret_group', 'key'), name='integrations_secretgroupassignment_unique_group_key'),
        ),
        migrations.AddConstraint(
            model_name='secretgroupassignment',
            constraint=models.UniqueConstraint(fields=('secret_group', 'secret'), name='integrations_secretgroupassignment_unique_group_secret'),
        ),
    ]
