CAPABILITY_AGENT_MODEL = "agent:model"
CAPABILITY_AGENT_TOOL = "agent:tool"
CAPABILITY_TRIGGER_WEBHOOK = "trigger:webhook"
CAPABILITY_TRIGGER_MANUAL = "trigger:manual"
CAPABILITY_TRIGGER_SCHEDULE = "trigger:schedule"

__all__ = (
    "CAPABILITY_AGENT_MODEL",
    "CAPABILITY_AGENT_TOOL",
    "CAPABILITY_TRIGGER_MANUAL",
    "CAPABILITY_TRIGGER_SCHEDULE",
    "CAPABILITY_TRIGGER_WEBHOOK",
)
