from .alertmanager_webhook import TRIGGER_DEFINITION as ALERTMANAGER_WEBHOOK_TRIGGER_DEFINITION
from .kibana_webhook import TRIGGER_DEFINITION as KIBANA_WEBHOOK_TRIGGER_DEFINITION

__all__ = [
    "ALERTMANAGER_WEBHOOK_TRIGGER_DEFINITION",
    "KIBANA_WEBHOOK_TRIGGER_DEFINITION",
]
