# Generated by Django 5.2.12 on 2026-03-29 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('users', '0002_backfill_user_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.environment')),
                ('groups', models.ManyToManyField(blank=True, related_name='memberships', to='users.group')),
                ('object_permissions', models.ManyToManyField(blank=True, related_name='memberships', to='users.objectpermission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.workspace')),
            ],
            options={
                'ordering': ('user__username', 'organization__name', 'workspace__name', 'environment__name'),
            },
        ),
        migrations.AddField(
            model_name='token',
            name='scope_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='users.membership'),
        ),
    ]
