# Generated by Django 5.2.12 on 2026-03-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group_created_group_last_updated_membership_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
