from django.urls import path

from .views import (
    WorkflowConnectionChangelogView,
    WorkflowConnectionCreateView,
    WorkflowConnectionDeleteView,
    WorkflowConnectionDetailView,
    WorkflowConnectionListView,
    WorkflowConnectionOpenAIOAuthCallbackView,
    WorkflowConnectionOpenAIOAuthPollView,
    WorkflowConnectionOpenAIOAuthStartView,
    WorkflowConnectionPopupCompleteView,
    WorkflowConnectionUpdateView,
    WorkflowChangelogView,
    WorkflowCreateView,
    WorkflowDeleteView,
    WorkflowDesignerConnectionsView,
    WorkflowDesignerSaveView,
    WorkflowDesignerView,
    WorkflowDesignerNodeRunView,
    WorkflowDesignerRunView,
    WorkflowDesignerRunStatusView,
    WorkflowDetailView,
    WorkflowListView,
    WorkflowUpdateView,
    WorkflowWebhookTriggerView,
)


urlpatterns = [
    path("workflow-connections/", WorkflowConnectionListView.as_view(), name="workflowconnection_list"),
    path("workflow-connections/add/", WorkflowConnectionCreateView.as_view(), name="workflowconnection_add"),
    path("workflow-connections/<int:pk>/", WorkflowConnectionDetailView.as_view(), name="workflowconnection_detail"),
    path(
        "workflow-connections/<int:pk>/popup-complete/",
        WorkflowConnectionPopupCompleteView.as_view(),
        name="workflowconnection_popup_complete",
    ),
    path(
        "workflow-connections/<int:pk>/changelog/",
        WorkflowConnectionChangelogView.as_view(),
        name="workflowconnection_changelog",
    ),
    path("workflow-connections/<int:pk>/edit/", WorkflowConnectionUpdateView.as_view(), name="workflowconnection_edit"),
    path(
        "workflow-connections/<int:pk>/oauth/openai/start/",
        WorkflowConnectionOpenAIOAuthStartView.as_view(),
        name="workflowconnection_openai_oauth_start",
    ),
    path(
        "workflow-connections/oauth/openai/device/<str:session_token>/poll/",
        WorkflowConnectionOpenAIOAuthPollView.as_view(),
        name="workflowconnection_openai_oauth_poll",
    ),
    path(
        "workflow-connections/oauth/openai/callback/",
        WorkflowConnectionOpenAIOAuthCallbackView.as_view(),
        name="workflowconnection_openai_oauth_callback",
    ),
    path(
        "workflow-connections/<int:pk>/delete/",
        WorkflowConnectionDeleteView.as_view(),
        name="workflowconnection_delete",
    ),
    path("workflows/", WorkflowListView.as_view(), name="workflow_list"),
    path("workflows/add/", WorkflowCreateView.as_view(), name="workflow_add"),
    path("workflows/<int:pk>/", WorkflowDetailView.as_view(), name="workflow_detail"),
    path("workflows/<int:pk>/designer/", WorkflowDesignerView.as_view(), name="workflow_designer"),
    path("workflows/<int:pk>/designer/save/", WorkflowDesignerSaveView.as_view(), name="workflow_designer_save"),
    path("workflows/<int:pk>/designer/connections/", WorkflowDesignerConnectionsView.as_view(), name="workflow_designer_connections"),
    path("workflows/<int:pk>/designer/run/", WorkflowDesignerRunView.as_view(), name="workflow_designer_run"),
    path(
        "workflows/<int:pk>/designer/runs/<int:run_id>/",
        WorkflowDesignerRunStatusView.as_view(),
        name="workflow_designer_run_status",
    ),
    path(
        "workflows/<int:pk>/designer/nodes/<str:node_id>/run/",
        WorkflowDesignerNodeRunView.as_view(),
        name="workflow_designer_node_run",
    ),
    path("webhooks/", WorkflowWebhookTriggerView.as_view(), name="workflow_webhook_trigger_public_base"),
    path(
        "webhooks/<path:webhook_path>/",
        WorkflowWebhookTriggerView.as_view(),
        name="workflow_webhook_trigger_public",
    ),
    path(
        "workflows/<int:pk>/trigger/webhook/",
        WorkflowWebhookTriggerView.as_view(),
        name="workflow_webhook_trigger_legacy",
    ),
    path(
        "workflows/<int:pk>/trigger/webhook/<path:webhook_path>/",
        WorkflowWebhookTriggerView.as_view(),
        name="workflow_webhook_trigger_legacy_path",
    ),
    path("workflows/<int:pk>/changelog/", WorkflowChangelogView.as_view(), name="workflow_changelog"),
    path("workflows/<int:pk>/edit/", WorkflowUpdateView.as_view(), name="workflow_edit"),
    path("workflows/<int:pk>/delete/", WorkflowDeleteView.as_view(), name="workflow_delete"),
]
