# Generated by Django 5.2.12 on 2026-03-30 16:45

import automation.models.workflows
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_environment_created_environment_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('definition', models.JSONField(blank=True, default=automation.models.workflows._default_definition)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='tenancy.environment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='tenancy.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='tenancy.workspace')),
            ],
            options={
                'ordering': ('organization__name', 'workspace__name', 'environment__name', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('environment__isnull', False)), fields=('environment', 'name'), name='automation_workflow_unique_environment_name'), models.UniqueConstraint(condition=models.Q(('environment__isnull', True), ('workspace__isnull', False)), fields=('workspace', 'name'), name='automation_workflow_unique_workspace_name'), models.UniqueConstraint(condition=models.Q(('environment__isnull', True), ('workspace__isnull', True)), fields=('organization', 'name'), name='automation_workflow_unique_organization_name')],
            },
        ),
    ]
