# Generated by Codex on 2026-04-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_workflowrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_groups",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_groups",
                        to="tenancy.workspace",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_groups",
                        to="tenancy.environment",
                    ),
                ),
            ],
            options={
                "db_table": "integrations_secretgroup",
                "ordering": ("organization__name", "workspace__name", "environment__name", "name"),
            },
        ),
        migrations.AddConstraint(
            model_name="secretgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("environment__isnull", False)),
                fields=("environment", "name"),
                name="integrations_secretgroup_unique_environment_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("environment__isnull", True), ("workspace__isnull", False)),
                fields=("workspace", "name"),
                name="integrations_secretgroup_unique_workspace_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True), ("environment__isnull", True)),
                fields=("organization", "name"),
                name="integrations_secretgroup_unique_organization_name",
            ),
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("provider", models.SlugField(help_text="Registered secrets backend provider slug.", max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific retrieval parameters, not the secret value itself.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("last_rotated", models.DateTimeField(blank=True, null=True)),
                ("expires", models.DateTimeField(blank=True, null=True)),
                (
                    "secret_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="automation.secretgroup",
                    ),
                ),
            ],
            options={
                "db_table": "integrations_secret",
                "ordering": (
                    "secret_group__organization__name",
                    "secret_group__workspace__name",
                    "secret_group__environment__name",
                    "secret_group__name",
                    "name",
                ),
            },
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("secret_group", "name"),
                name="integrations_secret_unique_group_name",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="secret_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflows",
                to="automation.secretgroup",
            ),
        ),
    ]
