# Generated by Codex on 2026-04-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_workflow_secret_group"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflowrun",
            new_name="automation__workflo_1f46b4_idx",
            old_name="automation__workflow_95d726_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowrun",
            new_name="automation__organiz_16132c_idx",
            old_name="automation__organiz_0bd2b4_idx",
        ),
    ]
