# Generated by Codex on 2026-04-02

from django.db import migrations


def move_secret_content_types_to_automation(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    ContentType.objects.using(db_alias).filter(
        app_label="integrations",
        model__in=("secret", "secretgroup"),
    ).update(app_label="automation")


def move_secret_content_types_to_integrations(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    ContentType.objects.using(db_alias).filter(
        app_label="automation",
        model__in=("secret", "secretgroup"),
    ).update(app_label="integrations")


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("automation", "0004_rename_automation__workflow_95d726_idx_automation__workflo_1f46b4_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            move_secret_content_types_to_automation,
            reverse_code=move_secret_content_types_to_integrations,
        ),
    ]
