# Generated by Django 5.2.12 on 2026-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_move_secret_models_into_automation'),
        ('tenancy', '0002_environment_created_environment_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='secretgroup',
            name='integrations_secretgroup_unique_organization_name',
        ),
        migrations.AddConstraint(
            model_name='secretgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('environment__isnull', True), ('workspace__isnull', True)), fields=('organization', 'name'), name='integrations_secretgroup_unique_organization_name'),
        ),
    ]
