# Generated by Django 5.2.12 on 2026-04-03 07:35

import hashlib
import json
import django.db.models.deletion
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models


def _build_snapshot_checksum(*, definition, metadata):
    payload = json.dumps(
        {
            "definition": definition,
            "metadata": metadata,
        },
        cls=DjangoJSONEncoder,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def backfill_workflow_versions(apps, schema_editor):
    del schema_editor
    Workflow = apps.get_model("automation", "Workflow")
    WorkflowRun = apps.get_model("automation", "WorkflowRun")
    WorkflowVersion = apps.get_model("automation", "WorkflowVersion")

    version_ids_by_workflow_id = {}
    for workflow in Workflow.objects.all().iterator():
        definition = dict(workflow.definition or {})
        metadata = dict(workflow.metadata or {})
        workflow_version = WorkflowVersion.objects.create(
            workflow_id=workflow.pk,
            version=1,
            definition_checksum=_build_snapshot_checksum(
                definition=definition,
                metadata=metadata,
            ),
            definition=definition,
            metadata=metadata,
        )
        version_ids_by_workflow_id[workflow.pk] = workflow_version.pk

    for run in WorkflowRun.objects.filter(workflow_version__isnull=True).iterator():
        workflow_version_id = version_ids_by_workflow_id.get(run.workflow_id)
        if workflow_version_id is None:
            continue
        WorkflowRun.objects.filter(pk=run.pk).update(workflow_version_id=workflow_version_id)


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_remove_secretgroup_integrations_secretgroup_unique_organization_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.PositiveIntegerField()),
                ('definition_checksum', models.CharField(max_length=64)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='automation.workflow')),
            ],
            options={
                'ordering': ('workflow_id', '-version'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sequence', models.PositiveIntegerField()),
                ('node_id', models.CharField(max_length=255)),
                ('node_kind', models.CharField(max_length=50)),
                ('node_type', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='automation.workflowrun')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_runs', to='automation.workflowversion')),
            ],
            options={
                'ordering': ('run_id', 'sequence'),
            },
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='automation.workflowversion'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', 'definition_checksum'], name='automation__workflo_a0a939_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'version'), name='automation_workflowversion_unique_workflow_version'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'definition_checksum'), name='automation_workflowversion_unique_workflow_checksum'),
        ),
        migrations.AddIndex(
            model_name='workflowsteprun',
            index=models.Index(fields=['run', 'sequence'], name='automation__run_id_4fd4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowsteprun',
            index=models.Index(fields=['run', 'node_id'], name='automation__run_id_3a56b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowsteprun',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='automation_workflowsteprun_unique_run_sequence'),
        ),
        migrations.RunPython(backfill_workflow_versions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workflowrun',
            name='workflow_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='automation.workflowversion'),
        ),
    ]
