# Generated by Django 5.2.12 on 2026-04-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_workflowrun_scheduler_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='workflowversion',
            name='metadata',
        ),
    ]
