# Generated by Django 5.2.12 on 2026-04-03 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_remove_workflow_metadata_and_more'),
        ('tenancy', '0002_environment_created_environment_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('integration_id', models.SlugField(max_length=100)),
                ('connection_type', models.SlugField(max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('credential_secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_connections', to='automation.secret')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_connections', to='tenancy.environment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_connections', to='tenancy.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_connections', to='tenancy.workspace')),
            ],
            options={
                'ordering': ('organization__name', 'workspace__name', 'environment__name', 'integration_id', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('environment__isnull', False)), fields=('environment', 'integration_id', 'name'), name='automation_workflowconnection_unique_environment_name'), models.UniqueConstraint(condition=models.Q(('environment__isnull', True), ('workspace__isnull', False)), fields=('workspace', 'integration_id', 'name'), name='automation_workflowconnection_unique_workspace_name'), models.UniqueConstraint(condition=models.Q(('environment__isnull', True), ('workspace__isnull', True)), fields=('organization', 'integration_id', 'name'), name='automation_workflowconnection_unique_organization_name')],
            },
        ),
    ]
