# Generated by Django 5.2.12 on 2026-04-05 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_remove_workflowconnection_compat_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConnectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('state_values', models.JSONField(blank=True, default=dict)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='automation.workflowconnection')),
            ],
            options={
                'ordering': ('connection__name',),
            },
        ),
    ]
