# Generated by Django 5.2.12 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0015_workflowconnectionstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowconnection",
            name="data",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RemoveField(
            model_name="workflowconnection",
            name="secret_group",
        ),
        migrations.RemoveField(
            model_name="workflowconnection",
            name="field_values",
        ),
    ]
