# Generated by Django 5.2.12 on 2026-04-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_workflowconnection_direct_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretgroup',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='secretgroup',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='secretgroup',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='secret_group',
        ),
        migrations.DeleteModel(
            name='Secret',
        ),
        migrations.DeleteModel(
            name='SecretGroup',
        ),
    ]
