# Generated by Django 5.2.12 on 2026-04-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_remove_secretgroup_environment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowconnection',
            options={'ordering': ('organization__name', 'workspace__name', 'environment__name', 'integration_id', 'name'), 'verbose_name': 'credential', 'verbose_name_plural': 'credentials'},
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
